server:
  port: 8085

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.username}
    password: ${app.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
  datasource:
    url: ${postgres.url}
    username: ${postgres.username}
    password: ${postgres.password}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop