server:
  port: 8085

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
  datasource:
    url: ${postgres.url}
    username: ${postgres.username}
    password: ${postgres.password}
  jpa:
    generate-ddl: true
  autoconfigure:
    exclude: org.springframework.cloud.vault.config.VaultAutoConfiguration

app:
  verfication:
    base-url: https://e817-37-114-160-132.ngrok-free.app
