server:
  port: 8085

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${email.username}
    password: ${app.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

