server:
  port: 8085

spring:
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
  datasource:
    url: ${postgres.url}
    username: ${postgres.username}
    password: ${postgres.password}
  jpa:
    generate-ddl: true
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude: org.springframework.cloud.vault.config.VaultAutoConfiguration
  cloud:
    vault:
      enabled: false


bravo:
  api:
    key: ${bravo.api.key}

app:
  verification:
    base-url: https://faridtgbot.com
