name: Build and Deploy telegram bot

on:
  push:
    branches:
      - main


jobs:
  build-and-test:
    name: Build and Deploy Telegram bot
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: makes executable
        run: chmod +x ./gradlew

      - name: clean and build
        run: ./gradlew clean build

      - name: running tests
        run: ./gradlew test
